module.exports = englishCommand => {
    return englishCommand.replace('in rage', '레이지 중')
        .replace(/qcf/gi, '236')
        .replace(/qcb/gi, '214')
        .replace(/hcf/gi, '41236')
        .replace(/hcb/gi, '63214')
        .replace(/WR/gi, '666')
        .replace(/WS/gi, '기상')
        .replace(/SS/gi, '횡신 중')
        .replace(/1\+2/gi, 'AP')
        .replace(/3\+4/gi, 'AK')
        .replace(/1\+3/gi, 'AL')
        .replace(/2\+4/gi, 'AR')
        .replace(/1/gi, 'LP')
        .replace(/2/gi, 'RP')
        .replace(/3/gi, 'LK')
        .replace(/4/gi, 'RK')
        .replace(/d\/b/gi, '1')
        .replace(/d\/f/gi, '3')
        .replace(/u\/b/gi, '7')
        .replace(/u\/f/gi, '9')
        .replace(/d/gi, '2')
        .replace(/b/gi, '4')
        .replace(/f/gi, '6')
        .replace(/u/gi, '8')
        .replace(/, /gi, ' ')
        .replace(/\+/, '');
}